baseURL = "https://lbarasti.github.io/"
languageCode = "en-gb"
title = "a polyglot's hacks"
[Params]
  Author = "Lorenzo Barasti"
  disqusShortname = "lbarasti-github-io"
  GoogleAnalyticsUserID = "UA-97340845-1"